### PR TITLE
Updated Packer to v1.5.2

### PR DESCRIPTION
**Pull request by hectorm**
To solve #41, I have applied the changes [mentioned in the Packer documentation](https://www.packer.io/guides/hcl/component-object-spec), however there are still several problems:

  * When using the plugin it produces a permission denied error (it seems that this is not the only case, see wata727/packer-post-processor-amazon-ami-management#59 and hashicorp/packer#8527).
    <details><summary>crash.log</summary>
    
    ```
    1970/01/01 00:00:00 [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 [DEBUG] Discovered plugin: arm-image = /usr/local/bin/packer-builder-arm-image
    1970/01/01 00:00:00 using external builders [arm-image]
    1970/01/01 00:00:00 Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 Plugin could not be found at  (exec: "": executable file not found in $PATH). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin []string{"/usr/local/bin"}
    1970/01/01 00:00:00 Plugin could not be found at /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell (exec: "/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell": stat /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell: no such file or directory). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin/packer
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
    1970/01/01 00:00:00 Waiting for RPC address for: /usr/local/bin/packer
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin190395704
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Waiting for connection...
    1970/01/01 00:00:00 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin190395704
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Serving a plugin connection...
    1970/01/01 00:00:00 Plugin could not be found at /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell (exec: "/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell": stat /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell: no such file or directory). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin/packer
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
    1970/01/01 00:00:00 Waiting for RPC address for: /usr/local/bin/packer
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin084891713
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Waiting for connection...
    1970/01/01 00:00:00 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin084891713
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Serving a plugin connection...
    1970/01/01 00:00:00 Plugin could not be found at /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell (exec: "/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell": stat /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell: no such file or directory). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin/packer
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
    1970/01/01 00:00:00 Waiting for RPC address for: /usr/local/bin/packer
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin290431505
    1970/01/01 00:00:00 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin290431505
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Waiting for connection...
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Serving a plugin connection...
    1970/01/01 00:00:00 Plugin could not be found at /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell (exec: "/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell": stat /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell: no such file or directory). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin/packer
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
    1970/01/01 00:00:00 Waiting for RPC address for: /usr/local/bin/packer
    1970/01/01 00:00:00 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin435717925
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin435717925
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Waiting for connection...
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Serving a plugin connection...
    1970/01/01 00:00:00 Plugin could not be found at /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell (exec: "/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell": stat /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell: no such file or directory). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin/packer
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
    1970/01/01 00:00:00 Waiting for RPC address for: /usr/local/bin/packer
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin996160860
    1970/01/01 00:00:00 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin996160860
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Waiting for connection...
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Serving a plugin connection...
    1970/01/01 00:00:00 Plugin could not be found at /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell (exec: "/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell": stat /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell: no such file or directory). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin/packer
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
    1970/01/01 00:00:00 Waiting for RPC address for: /usr/local/bin/packer
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin565080631
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Waiting for connection...
    1970/01/01 00:00:00 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin565080631
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Serving a plugin connection...
    1970/01/01 00:00:00 Plugin could not be found at /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell (exec: "/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell": stat /usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell: no such file or directory). Checking same directory as executable.
    1970/01/01 00:00:00 Current exe path: /usr/local/bin/packer
    1970/01/01 00:00:00 Creating plugin client for path: /usr/local/bin/packer
    1970/01/01 00:00:00 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
    1970/01/01 00:00:00 Waiting for RPC address for: /usr/local/bin/packer
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [INFO] Packer version: 1.5.1 [go1.13.5 linux amd64]
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Attempting to open config file: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Setting cache directory: ~REDACTED~/packer_cache
    1970/01/01 00:00:00 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin954022891
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Waiting for connection...
    1970/01/01 00:00:00 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin954022891
    1970/01/01 00:00:00 packer-provisioner-shell plugin: Serving a plugin connection...
    1970/01/01 00:00:00 ui: ???????: Failed to load source type
    
      on raspbian.pkr.hcl line 1, in source "arm-image" "raspbian":
       1: source "arm-image" "raspbian" {
    
    fork/exec /usr/local/bin: permission denied
    
    1970/01/01 00:00:00 ui: [1;32marm-image: output will be in this color.[0m
    1970/01/01 00:00:00 ui: 
    1970/01/01 00:00:00 Build debug mode: false
    1970/01/01 00:00:00 Force build: false
    1970/01/01 00:00:00 On error: 
    1970/01/01 00:00:00 Preparing build: arm-image
    1970/01/01 00:00:00 waiting for all plugin processes to complete...
    1970/01/01 00:00:00 /usr/local/bin/packer: plugin process exited
    1970/01/01 00:00:00 /usr/local/bin/packer: plugin process exited
    1970/01/01 00:00:00 /usr/local/bin/packer: plugin process exited
    1970/01/01 00:00:00 /usr/local/bin/packer: plugin process exited
    1970/01/01 00:00:00 /usr/local/bin/packer: plugin process exited
    1970/01/01 00:00:00 /usr/local/bin/packer: plugin process exited
    1970/01/01 00:00:00 /usr/local/bin/packer: plugin process exited
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xd770bd]
    
    goroutine 1 [running]:
    github.com/hashicorp/packer/packer.(*CoreBuild).Prepare(0xc0001763c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/Users/mmarsh/Projects/packer/packer/build.go:153 +0x4cd
    github.com/hashicorp/packer/command.(*BuildCommand).RunContext(0xc0002c82a0, 0x47fa500, 0xc0002ce040, 0xc0000b2170, 0x1, 0x1, 0xc0002ce040)
    	/Users/mmarsh/Projects/packer/command/build.go:237 +0x7ae
    github.com/hashicorp/packer/command.(*BuildCommand).Run(0xc0002c82a0, 0xc0000b2170, 0x1, 0x1, 0x0)
    	/Users/mmarsh/Projects/packer/command/build.go:55 +0x201
    github.com/mitchellh/cli.(*CLI).Run(0xc00031c280, 0xc00031c280, 0x1, 0x1)
    	/Users/mmarsh/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1da
    main.wrappedMain(0x0)
    	/Users/mmarsh/Projects/packer/main.go:238 +0x853
    main.realMain(0x0)
    	/Users/mmarsh/Projects/packer/main.go:124 +0xbb
    main.main()
    	/Users/mmarsh/Projects/packer/main.go:34 +0x22
    ```
    
    </details>
    
  * The auto-generated `builder.hcl2spec.go` file should have the following changes, however I don't know how to set the appropriate annotations so I don't need to manually edit the file.
    <details><summary>builder-hcl2spec-image_type.patch</summary>
    
    ```diff
    --- a/pkg/builder/builder.hcl2spec.go	1970-01-01 00:00:00.000000000 +0000
    +++ b/pkg/builder/builder.hcl2spec.go	1970-01-01 00:00:00.000000000 +0000
    @@ -29,3 +29,3 @@
     	OutputFile             *string              `mapstructure:"output_filename" cty:"output_filename"`
    -	ImageType              utils.KnownImageType `mapstructure:"image_type" cty:"image_type"`
    +	ImageType              *utils.KnownImageType `mapstructure:"image_type" name:"image_type" cty:"image_type"`
     	ImageMounts            []string             `mapstructure:"image_mounts" cty:"image_mounts"`
    @@ -69,3 +69,3 @@
     		"output_filename":            &hcldec.AttrSpec{Name: "output_filename", Type: cty.String, Required: false},
    -		"image_type":                 &hcldec.AttrSpec{Name: "utils.KnownImageType", Type: cty.String, Required: false},
    +		"image_type":                 &hcldec.AttrSpec{Name: "image_type", Type: cty.String, Required: false},
     		"image_mounts":               &hcldec.AttrSpec{Name: "image_mounts", Type: cty.List(cty.String), Required: false},
    ```
    
    </details>
    
  * The `vendor` directory needs to be updated, I haven't included it to avoid polluting the PR.

### CODE REVIEW

**Comment by yuval-k** [comment]
looks good, can this be merged, or still WIP?

**Comment by hectorm** [comment]
Apparently the crash is due a bug in Packer that will be solved by hashicorp/packer#8543.

**Comment by yuval-k** [comment]
@hectorm  packer 1.5.2 with this fix should be release on Feb 5th; is it your preference to wait for the release?
i'm ok with depending on master, if you want to finish the PR; and i can update it to a released version later.

**Comment by hectorm** [comment]
I've no problem updating the PR. In fact, that's what I'm doing locally. I'll make time to work on this today or tomorrow.

In the meantime, feel free to make any changes you need to the PR. For example, I haven't solved the problem with the annotations.

**Comment by hectorm** [comment]
Done.

It seems that the problem with the annotations was due a bug in Packer that is fixed in master (hashicorp/packer@13ea97a1dfebf0980d45bbdc1a2148ae341b9840).

**Pull request merged**
