### PR TITLE
fix imports and revendor

### PR DESCRIPTION
**Pull request by SwampDragons**
Hi! I'm a maintainer over at Packer and I wanted to make this PR to make your life a tad easier -- we'll be releasing v1.7.0 tomorrow and it will include a backwards-breaking API change. This PR should be all you need to get yourself upgraded to work with v1.7.  

That said, there's a little more legwork for you to do if you want your plugin to be compatible with the `packer init` feature we'll also be implementing in that release. We have an upgrade guide here: https://github.com/hashicorp/packer/blob/master/website/content/guides/1.7-plugin-upgrade.mdx

I also noticed that in addition to changing import paths, there's one other, older, backwards breaking change this will cause for you: StepDownload from the commonsteps package now has a new checksumming format that removes the checksum "type" field and expects you to embed it directly in the checksum. I updated your docs and examples, and regenerated your HCL configspecs to make this work for you. 

Let me know if you have any issues!

### CODE REVIEW

**Comment by SwampDragons** [comment]
Hmm that's odd. locally generating and vendoring produces no further changes.

**Comment by rusenask** [comment]
> Hmm that's odd. locally generating and vendoring produces no further changes.

I think the issue is in the CI itself, it has vendor dir but also runs generate on them all https://github.com/solo-io/packer-builder-arm-image/blob/master/.github/workflows/pull_request.yaml#L27-L31

As for this branch, I get into some dependency issue:
```
 go mod tidy
go: github.com/hashicorp/packer-plugin-sdk@v0.0.13 requires
        github.com/hashicorp/packer@v1.6.7-0.20210208125835-f616955ebcb6 requires
        github.com/hashicorp/packer-plugin-sdk@v0.0.11 requires
        github.com/hashicorp/packer@v1.6.7-0.20210126105722-aef4ced967ec: invalid version: unknown revision aef4ced967ec
```
tried updating everything but not sure what should be the correct set of versions.

**Comment by SwampDragons** [comment]
I revendored to use sdk version 14. 

I was able to tidy and build successfully; let me know if you can too. Otherwise I'll keep tinkering. What version of golang are you on? I am on 1.16

**Comment by rusenask** [comment]
1.16 too, currently trying out https://github.com/mkaczanowski/packer-builder-arm, I will try your branch tomorrow as it's getting late

**Comment by yuval-k** [comment]
hi @SwampDragons Thank you very much for the PR!
I think code gen fails because you need to run `go mod tidy`

**Comment by SwampDragons** [comment]
Aha! your tests needed to call to mod tidy before the compare.

**Comment by SwampDragons** [comment]
Okay, I fixed the tests and cleaned up the git history so you aren't merging six "tidy??" commits :D

**Comment by yuval-k** [comment]
awesome, thank you so much @SwampDragons !

**Review by yuval-k — APPROVED** [review]

**Pull request merged**
