### PR TITLE
Disable decompressors again

### PR DESCRIPTION
**Pull request by joshuaspence**
After upgrading to Packer 1.7 I noticed that RaspiOS is being downloaded on every Packer run (as in #44). It appears that this regression was caused by #95, which upgrades to version 2 of `go-getter`.

### CODE REVIEW

**Comment by joshuaspence** [comment]
I'm having trouble figuring out why the tests are failing

**Comment by yuval-k** [comment]
thank you @joshuaspence ! 
try running `go mod tidy; go mod vendor` (using go 1.16) 
if that doest solve it, let me know and i'll merge this PR and figure it out the issue after it is merged

**Comment by joshuaspence** [comment]
Thanks for the suggestion @yuval-k but it didn't seem to work. In fact, I had already run those commands.

**Comment by yuval-k** [comment]
ok, i'm merging this and will figure this out later.
thanks @joshuaspence

**Pull request merged**
