### PR TITLE
Fix vagrant environment

### PR DESCRIPTION
**Pull request by mrtwnklr**
Some adjustments needed to be made to get the vagrant enviroment running after
* release of golang 1.14 (GOROOT points to wrong path) and
* changes introduced with #42 ("Plugin version 5, Ours: 4")

Now i am stuck at `vagrant provision --provision-with build-image` with the following error:

> ==> default: Running provisioner: build-image (shell)...
    default: Running: /tmp/vagrant-shell20200309-11909-9epypv.sh
    default: + set -e
    default: + export PACKERFILE=samples/raspbian_golang.json
    default: + PACKERFILE=samples/raspbian_golang.json
    default: + mkdir -p /home/vagrant/.packer.d/plugins
    default: + cp /vagrant/packer-builder-arm-image /home/vagrant/.packer.d/plugins/
    default: Attempting to build image
    default: + [[ ! -f /home/vagrant/.packer.d/plugins/packer-builder-arm-image ]]
    default: + echo 'Attempting to build image'
    default: ++ mktemp
    default: + PACKER_LOG=/tmp/tmp.T6Jd1Y1tyY
    default: + [[ -f /vagrant/samples/raspbian_golang.json ]]
    **default: + sudo packer build /vagrant/samples/raspbian_golang.json
    default: + tee /tmp/tmp.T6Jd1Y1tyY
    default: Failed to initialize build 'arm-image': error initializing builder 'arm-image': Unknown builder arm-image**
    default: 
    default: ==> Builds finished but no artifacts were created.

So `sudo packer build /vagrant/samples/raspbian_golang.json` fails when executed in `/home/vagrant`.

When changing directory to `/vagrant` before packer succeeds...:
```
vagrant ssh
cd /vagrant
sudo packer build /vagrant/samples/raspbian_golang.json
```
... but the resulting image file is not placed under `/home/vagrant` so the following lines to copy the file fail:

>    default: Build 'arm-image' finished.
    default: 
    **default: ==> Builds finished. The artifacts of successful builds are:
    default: --> arm-image: output-arm-image/image**
    default: ++ grep -Po '(?<=Build '\'').*(?='\'' finished.)' /tmp/tmp.h5dLO0dA1y
    default: + BUILD_NAME=arm-image
    default: ++ grep -Po '(?<=--> arm-image: ).*' /tmp/tmp.h5dLO0dA1y
    default: + IMAGE_PATH=output-arm-image/image
    default: + rm -f /tmp/tmp.h5dLO0dA1y
    **default: + [[ -f /home/vagrant/output-arm-image/image ]]
    default: + echo 'Error: Unable to find build artifact.'**
    default: Error: Unable to find build artifact.
    default: + exit

The shell script `provision-build-image.sh` has not changed since 2 years.
Does anyone has a clue?

### CODE REVIEW

**Comment by yuval-k** [comment]
i'm not sure as i'm not the original author. will try and take a look soon

**Comment by gtarnaras** [comment]
@mrtwnklr please have a look https://github.com/solo-io/packer-builder-arm-image/pull/71 as well. I changed this before checking any existing PRs and i just found yours. Instead of upgrading the version i changed the installation method to simply use wget and then move the binary to the $PATH . Go lang is a hard depenency here so we will not hit a compatibility issue in the future with this method. Other than that we should have some control over the Go version installed. About your image problem not being copied in the correct dir you'll need guest-additions for Virtualbox (i guess you already figured that out from your README update). However, @yuval-k  it might worth use a different image in the Vagrantfile which has guest-additions pre-installed.

**Comment by yuval-k** [comment]
i use docker to run this and have no vagrant setup; so I don't have an opinion here

**Comment by yuval-k** [comment]
closing this as stale; please re-open if you plan to prosue this

**Comment by mrtwnklr** [comment]
@gtarnaras thank you. #71 does work for me too!

**Pull request closed without merging**
